Prueba de creación de SonarCloud

diff --git a/.github/workflows/pipelineCiCD.yml b/.github/workflows/pipelineCiCD.yml
--- a/.github/workflows/pipelineCiCD.yml
+++ b/.github/workflows/pipelineCiCD.yml
@@ -5,11 +5,40 @@ on:
   workflow_dispatch:
 
 jobs:
-  Analysis:
-    runs-on: ubuntu-latest
+  SAST:
+    name: Static Application Security Testing (SAST) con SonarCloud
+    runs-on: ubuntu-24.04
 
     steps:
-          
-      - name: Hola mundo
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Set Environment Variables
+        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
+
+      - name: Validate Project in SonarCloud
+        id: validateProjectOnSonar
         run: |
-          echo "hola mundo"
+          PROJECT_NAME="${{ github.event.repository.name }}"
+          ORGANIZATION="glemosas"
+          BRANCH_NAME="${{ github.ref_name }}"
+          
+          echo "Verificando si el proyecto '${PROJECT_NAME}' ya existe en SonarCloud..."
+
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
+            "https://sonarcloud.io/api/projects/create" \
+            -d "name=${PROJECT_NAME}" \
+            -d "project=${PROJECT_NAME}" \
+            -d "organization=${ORGANIZATION}" \
+            -d "visibility=public")
+
+          if [ "$response" -eq 400 ]; then
+            echo "Proyecto '${PROJECT_NAME}' ya existe en SonarCloud"
+            echo "project_created=false" >> $GITHUB_ENV
+          elif [ "$response" -eq 200 ]; then
+            echo "Proyecto '${PROJECT_NAME}' creado exitosamente en SonarCloud"
+            echo "project_created=true" >> $GITHUB_ENV
+          else
+            echo "Error al crear el proyecto en SonarCloud. Código de respuesta: $response"
+            exit 1
+          fi
