Prueba de despliegue

diff --git a/.github/workflows/pipelineCiCD.yml b/.github/workflows/pipelineCiCD.yml
--- a/.github/workflows/pipelineCiCD.yml
+++ b/.github/workflows/pipelineCiCD.yml
@@ -274,7 +274,77 @@ jobs:
           fi
 
       - name: Subir reporte de Trivy como artefacto
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: trivyreport
           path: trivyreport.json
+          
+  Deploy:
+      needs: DockerScan
+      name: Desplegar Contenedor Docker
+      runs-on: ubuntu-24.04
+      env:
+        IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/laboratorio_final_glemos2
+        CONTAINER_NAME: laboratorio_glemos
+      steps:
+        - name: Docker Login
+          uses: docker/login-action@v3.0.0
+          with:
+            username: ${{ secrets.DOCKER_USERNAME }}
+            password: ${{ secrets.DOCKER_PASSWORD }}
+
+        - name: Pull Docker Image
+          run: docker pull $IMAGE_NAME:latest
+
+        - name: Detener y eliminar contenedor existente
+          run: |
+            if docker stop $CONTAINER_NAME; then
+              echo "Contenedor detenido correctamente."
+            else
+              echo "No se pudo detener el contenedor, podría no estar ejecutándose."
+            fi
+            if docker rm $CONTAINER_NAME; then
+              echo "Contenedor eliminado correctamente."
+            else
+              echo "No se pudo eliminar el contenedor, podría no existir."
+            fi
+          continue-on-error: true
+
+        - name: Desplegar Contenedor
+          run: |
+            docker run -d \
+              --restart=always \
+              -p 3000:3000 \
+              --name $CONTAINER_NAME \
+              $IMAGE_NAME:latest
+
+        - name: Esperar a que el contenedor esté saludable
+          run: |
+            echo "Esperando a que el contenedor esté en estado saludable..."
+            retries=10
+            while [ "$retries" -gt 0 ]; do
+              if [ "$(docker inspect --format='{{.State.Health.Status}}' $CONTAINER_NAME)" == "healthy" ]; then
+                echo "✅ Contenedor está saludable."
+                break
+              fi
+              sleep 3
+              retries=$((retries - 1))
+            done
+            if [ "$retries" -eq 0 ]; then
+              echo "❌ El contenedor no alcanzó el estado saludable. Revisar logs."
+              docker logs $CONTAINER_NAME
+              exit 1
+            fi
+
+        - name: Chequeo de Estado de Contenedor
+          run: |
+            sleep 10
+            if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
+              echo "✅ Contenedor desplegado exitosamente"
+              docker ps
+              echo "La aplicación debería estar disponible en http://localhost:3000"
+            else
+              echo "❌ Error en el despliegue del contenedor"
+              docker logs $CONTAINER_NAME
+              exit 1
+            fi
