Incluye Vulnerabilidades Trivy explicitas y mejora de variables

diff --git a/.github/workflows/pipelineCiCD.yml b/.github/workflows/pipelineCiCD.yml
--- a/.github/workflows/pipelineCiCD.yml
+++ b/.github/workflows/pipelineCiCD.yml
@@ -115,7 +115,7 @@ jobs:
 
       # Subir reporte del análisis
       - name: Subir reporte
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: dependency-check-report
           path: ./reports
@@ -154,8 +154,10 @@ jobs:
 
   DockerBuild:
     needs: SCA
-    name: Build Image Docker
+    name: Build Docker Image
     runs-on: ubuntu-24.04
+    env:
+      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/laboratorio_final_glemos
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -166,31 +168,56 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           
-      - name: Build image
-        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/laboratorio_final_glemos:latest .
+      - name: Build Docker Image
+        run: |
+          docker build -t $IMAGE_NAME:latest \
+                       -t $IMAGE_NAME:${{ github.sha }} .
 
-      - name: Push image a Docker
-        run: docker push ${{ secrets.DOCKER_USERNAME }}/laboratorio_final_glemos
+      - name: Push Docker Image
+        run: |
+          docker push $IMAGE_NAME:latest
+          docker push $IMAGE_NAME:${{ github.sha }}
 
   DockerScan:
     needs: DockerBuild
-    name: Scan Image Docker
+    name: Scan Docker Image
     runs-on: ubuntu-24.04
+    env:
+      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/laboratorio_final_glemos
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
       - name: Docker Login
         uses: docker/login-action@v3.0.0
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Pull Docker Image
-        run: docker pull ${{ secrets.DOCKER_USERNAME }}/laboratorio_final_glemos:latest
-        
-      - name: Run Trivy Scan
-        uses: aquasecurity/trivy-action@master
+      - name: Escaneo de Docker Image con Trivy
+        run: |
+          trivy image $IMAGE_NAME:latest --format json --output trivy-scan-report.json \
+          --severity CRITICAL,HIGH,MEDIUM,LOW || true
+
+      - name: Conteo de Vulnerabilidades
+        run: |
+          CRITICAL=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "CRITICAL")] | length' trivy-scan-report.json)
+          HIGH=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "HIGH")] | length' trivy-scan-report.json)
+          MEDIUM=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "MEDIUM")] | length' trivy-scan-report.json)
+          LOW=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "LOW")] | length' trivy-scan-report.json)
+          TOTAL=$((CRITICAL + HIGH + MEDIUM + LOW))
+
+          echo "Vulnerabilities Summary:"
+          echo "Critical: $CRITICAL"
+          echo "High: $HIGH"
+          echo "Medium: $MEDIUM"
+          echo "Low: $LOW"
+          echo "Total: $TOTAL"
+
+          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ] || [ "$MEDIUM" -gt 0 ]; then
+            echo "Critical, High, or Medium vulnerabilities detected! Failing pipeline..."
+            exit 1
+          fi
+
+      - name: Upload Trivy Report
+        uses: actions/upload-artifact@v3
         with:
-          image-ref: '${{ secrets.DOCKER_USERNAME }}/laboratorio_final_glemos:latest'
-          format: 'table'
+          name: Trivy Scan Report
+          path: trivy-scan-report.json
